UICR-8-Bootstrap-Components
unicoderns/uiExample pull request #2
Opened 2020-09-28 15:19 UTC by IsaZG

1. In this pr I added Alerts, Badges, Breadcrumbs, Buttons and Button Groups from Boostrap Documentation: https://getbootstrap.com/docs/4.5/components/alerts/.
2.  It just the scss and html code.

2020-10-07 00:35 UTC, chrissmejia requested changes
Awesome job, just need a couple of changes

2020-10-07 00:35 UTC, chrissmejia commented on src/App.vue
> +    <AlertComponent msg="Welcome to Unicoderns Interface Component" />
Hi Isa, let's please follow the next pattern for names `<ui-component>` this for example could be `<ui-alert>`

2020-10-07 00:35 UTC, chrissmejia commented on src/App.vue
> +    <BadgeComponent />
Example `<ui-badge>`

2020-10-07 00:35 UTC, chrissmejia commented on package.json
> +    "jquery": "^3.5.1",
We will be removing this dependency at some point, JFYI.

2020-10-07 00:35 UTC, chrissmejia commented on src/components/BadgeComponent.vue
> +    <h1>Example heading <span class="badge badge-secondary">New</span></h1>
Please create a `<ui-badge>` that take a prop (param) indicating the kind, ex: secondary, success, etc

2020-10-07 00:35 UTC, chrissmejia commented on src/App.vue
> +    <AlertComponent msg="Welcome to Unicoderns Interface Component" />
I saw you have been grouping by kind, so, for alerts the component can be called `<ui-alerts>` and inside contain multiple `<ui-alert>`

2020-10-07 00:35 UTC, chrissmejia commented on src/components/ButtonComponent.vue
> +    <button type="button" class="btn btn-outline-primary">Primary</button>
Let's do something like <ui-button type="primary" />

2020-10-12 12:22 UTC, IsaZG commented
Hi @chrissmejia  I'm going to create another branch and pr and worked with the new commit you created yesterday, then I will send new pr's. Thank you.

2020-10-12 12:22 UTC, closed without merging